spring:
  application:
    name: support-service
  datasource:
    url: jdbc:mysql://localhost:3306/job_find_support?createDatabaseIfNotExist=true
    username: root
    password: 1crazy!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 7784

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME:your_cloud_name}
  api_key: ${CLOUDINARY_API_KEY:your_api_key}
  api_secret: ${CLOUDINARY_API_SECRET:your_api_secret}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7800/eureka/
